### ISSUE TITLE
Archive a PR branch when the PR is closed

### ISSUE THREAD

**Issue by epompeii** [bencherdev/bencher#499]
Currently, the only way to archive a dimension with the CLI is either through `bencher run` under certain conditions [with `--branch-start-point` or `--branch-reset`](https://bencher.dev/docs/explanation/branch-selection/) or using [the `bencher branch update` sub-command](https://bencher.dev/docs/api/projects/branches/#patch-v0projectsprojectbranchesbranch).

In CI, one needs to be able to take in `${{ github.head_ref }}` as the argument for the branch to be archived. However, `bencher branch update` only works on the branch slug or UUID. Therefore a way to archive a branch based off its name needs to be added. Something like `bencher branch archive BRANCH-NAME`.

An example should also be added to the docs that runs when a PR is closed:

```yml
on:
  pull_request:
    types: [closed]

jobs:
  archive_pr_branch:
    name: Archive Bencher PR Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Archive Bencher Branch
        run: |
          bencher archive \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --project my-project \
          --branch '${{ github.head_ref }}' 
``` 

For consistency, go ahead and implement this same sub-command for all dimensions: Branches, Testbeds, Benchmarks, and Measures.
